# Generated by Django 4.2.7 on 2024-01-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipo_jugador/media/equipo')),
                ('detalles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jugador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('numero_ficha', models.IntegerField(blank=True, default=0, null=True)),
                ('jugador_equipo', models.ManyToManyField(related_name='jugadores', to='equipo_jugador.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo_torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo_jugador.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.torneo')),
            ],
        ),
    ]
