# Generated by Django 4.2.7 on 2024-01-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
        ('equipo_jugador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo_torneo',
            name='torneo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo_equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torneos.torneo'),
        ),
    ]
